[tool.pyright]
stubPath = "src/stubs"
pythonVersion = "3.11"
pythonPlatform = "All"
typeCheckingMode = "strict"
ignore = ["**/.venv"]

[tool.black]
target-version = ['py311']
preview = true
enable-unstable-feature = ["string_processing"]

[tool.ruff]
extend-include = ["*.ipynb"]
target-version = "py311"
fix = true
required-version = ">=0.5.7"

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
preview = true

[tool.ruff.lint]
select = ["ALL"]
extend-select = ["I"]
ignore = [
    # Ignore missing blank before between class name and docstring
    "D203", 
    # Do not require a description after summary line in docstring
    "D205",
    # Do not require summary line to be located on first physical line of docstring
    "D212", 
    # Do not require docstring section names to end with colon
    "D416",  
    # Ignore TODO notes
    "FIX002",
    "TD002",
    "TD003",
    "TD004",
    # Ignore missing copyright notice
    "CPY001", 
    # Ignore function signatures with too many arguments
    "PLR0913",
    # ignore function signatures with too many positional arguments
    "PLR0917", 
    # Ignore boolean positional argument in function signature
    "FBT002", 
    "FBT001",
]
unfixable = ["F401"]
preview = true

[tool.ruff.lint.flake8-annotations]
#ignore-fully-untyped = true

[tool.ruff.lint.isort]
relative-imports-order = "closest-to-furthest"
section-order = [
    "future",
    "typing",
    "standard-library",
    "third-party",
    "networking",
    "data-science",
    "machine-learning",
    "audio",
    "visualisation",
    "first-party",
    "base",
    "vc",
    "backend",
    "frontend",
    "main",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"typing" = ["typing", "typing_extensions"]
"networking" = [
    "requests",
    "yt_dlp",
    "deemix",
    "wget",
    "flask",
    "beautifulsoup4",
    "pypresence",
]
"data-science" = [
    "numpy", 
    "scipy", 
    "matplotlib", 
    "tqdm", 
    "pandas", 
    "gradio"
]
"machine-learning" = [
    "torch",
    "torchaudio",
    "torchcrepe",
    "fairseq",
    "faiss",
    "tensorboard",
    "torchfcpe",
    "local_attention",
    "libf0",
    "einops",
    "numba",
]
"audio" = [
    "ffmpeg",
    "soundfile",
    "librosa",
    "sox",
    "pydub",
    "pedalboard",
    "audio_separator",
    "parselmouth",
    "pyworld",
    "noisereduce",
    "audio_upscaler",
    "edge_tts",
    "ffmpy",
]
"base" = ["common", "typing_extra"]
"vc" = ["vc"]
"backend" = ["backend"]
"frontend" = ["frontend"]
"main" = ["app", "cli", "init"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 72
